export enum Icon {
  X_MARK = 'X_MARK',
  PEN = 'PEN',
  TRASH_CAN = 'TRASH_CAN',
  BARS = 'BARS',
  PLUS = 'PLUS',
  MINUS = 'MINUS',
  HORIZONTAL_ARROWS = 'HORIZONTAL_ARROWS',
  TWO_SHEETS_COPY = 'TWO_SHEETS_COPY',
  VERTICAL_OPPOSING_TRIANGLES = 'VERTICAL_OPPOSING_TRIANGLES',
  CIRCLE_QUESTION = 'CIRCLE_QUESTION',
  SQUARE = 'SQUARE',
  SQUARE_CHECK = 'SQUARE_CHECK',
  SQUARE_MINUS = 'SQUARE_MINUS',
  CHECK = 'CHECK',
  DOWNWARD_TRIANGLE = 'DOWNWARD_TRIANGLE',
  UPWARD_TRIANGLE = 'UPWARD_TRIANGLE',
  TRIANGLE_EXCLAMATION = 'TRIANGLE_EXCLAMATION',
  CIRCLE_EXCLAMATION = 'CIRCLE_EXCLAMATION',
}

export enum IconSize {
  XS = 'xs',
  S = 'sm',
  M = '1x',
  L = 'lg',
  XL = 'xl',
  XXL = '2xl',
}
