export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  RESET = 'RESET',
  TAKEN = 'TAKEN',
  SET_NEXT = 'SET_NEXT',
  INFINITE_PIECE_ADDED = 'INFINITE_PIECE_ADDED',
  PART_INSERTED_AS_ON_AIR = 'PART_INSERTED_AS_ON_AIR',
  PART_INSERTED_AS_NEXT = 'PART_INSERTED_AS_NEXT',
  PIECE_INSERTED = 'PIECE_INSERTED',
  RUNDOWN_CREATED = 'RUNDOWN_CREATED',
  RUNDOWN_UPDATED = 'RUNDOWN_UPDATED',
  RUNDOWN_DELETED = 'RUNDOWN_DELETED',
}
