export enum RundownEventType {
  ACTIVATED = 'ACTIVATED',
  DEACTIVATED = 'DEACTIVATED',
  RESET = 'RESET',
  TAKEN = 'TAKEN',
  SET_NEXT = 'SET_NEXT',
  INFINITE_PIECE_ADDED = 'INFINITE_PIECE_ADDED',

  RUNDOWN_CREATED = 'RUNDOWN_CREATED',
  RUNDOWN_UPDATED = 'RUNDOWN_UPDATED',
  RUNDOWN_DELETED = 'RUNDOWN_DELETED',

  SEGMENT_CREATED = 'SEGMENT_CREATED',
  SEGMENT_UPDATED = 'SEGMENT_UPDATED',
  SEGMENT_DELETED = 'SEGMENT_DELETED',

  PART_CREATED = 'PART_CREATED',
  PART_UPDATED = 'PART_UPDATED',
  PART_DELETED = 'PART_DELETED'
}
