name: 'Check'
on:
  pull_request:
jobs:
  setup:
    runs-on: 'ubuntu-latest'
    name: 'Setup and install dependencies'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Get Yarn cache directory path'
        id: 'yarn-cache-directory-path'
        run: 'echo "directory=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT'
      - name: 'Cache Yarn cache directory'
        uses: 'actions/cache@v4'
        with:
          path: ${{ steps.yarn-cache-directory-path.outputs.directory }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Install dependencies'
        run: 'yarn install'

  build:
    needs: setup
    runs-on: 'ubuntu-latest'
    name: 'Build'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Build'
        run: 'yarn build'

  test:
    needs: setup
    runs-on: 'ubuntu-latest'
    name: 'Test'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Test'
        run: 'yarn test'

  lint:
    needs: setup
    runs-on: 'ubuntu-latest'
    name: 'Lint'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Lint'
        run: 'yarn lint'

  validate:
    needs: setup
    runs-on: 'ubuntu-latest'
    name: 'Validate dependencies'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Validate dependencies'
        run: 'yarn validate'
